modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/unilock/deslabification/issues"

[[mods]]
modId = "deslabification"
version = "${version}"
displayName = "Deslabification"
displayURL = "https://github.com/unilock/deslabification"
authors = "unilock"
displayTest = "IGNORE_SERVER_VERSION"
description = '''Automatically adds recipes to convert slabs back to blocks'''

[[dependencies.deslabification]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
